# .github/workflows/tauri.yml
jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: tauri-apps/tauri-action@v0
        with:
          args: --target x86_64-unknown-linux-gnu
