name: Build and Test Tauri Linux AppImage

on:
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    name: Build + Test AppImage

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-unknown-linux-gnu

      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            build-essential \
            curl \
            wget \
            libssl-dev \
            libgtk-3-dev \
            squashfs-tools \
            patchelf \
            librsvg2-dev \
            libappindicator3-dev \
            libwebkit2gtk-4.1-dev || true  # 避免因为版本问题失败

      - name: Install frontend dependencies
        run: npm install --legacy-peer-deps

      - name: Build Tauri App (AppImage)
        uses: tauri-apps/tauri-action@v0
        with:
          args: --target x86_64-unknown-linux-gnu
        env:
          TAURI_PRIVATE_KEY: ${{ secrets.TAURI_PRIVATE_KEY }}
          TAURI_KEY_PASSWORD: ${{ secrets.TAURI_KEY_PASSWORD }}

      - name: Upload AppImage artifact
        uses: actions/upload-artifact@v4
        with:
          name: tauri-appimage
          path: src-tauri/target/release/bundle/appimage/*.AppImage

      - name: Test AppImage launch
        run: |
          chmod +x src-tauri/target/release/bundle/appimage/*.AppImage
          ./src-tauri/target/release/bundle/appimage/*.AppImage --no-sandbox > run.log 2>&1 &
          sleep 5
          if pgrep -f ".AppImage" > /dev/null; then
            echo "✅ AppImage launched successfully"
          else
            echo "❌ AppImage failed to launch. Log output:"
            cat run.log
            exit 1
          fi
